### ISSUE TITLE
New metric: Occasional Contributors

### ISSUE THREAD

**Issue by jwflory** [chaoss/wg-common#119]
_Continued discussion from [**gitlab:cauldronio/cauldron#661**](https://gitlab.com/cauldronio/cauldron/-/issues/661) and conversation with @GeorgLink._

---

# Summary

Create a metric, or common definition, of what a drive-through contributor means.

# Background

CHAOSS has discussed the idea of "drive-by" contributors, "fly-by" contributions, and other metaphors for folks who come to make one contribution to a project, and then disappear. There is a strong negative connotation to "drive-by" contributors and it is not a common phrase outside of the United States. It leads to confusion when interpreting the meaning of the measure. To date, there does not seem to be a standard way of how we describe these kinds of contributors.

# Details

I propose a new metric to define `drive-through contributors`. This is the most widely-used term I see in place of `drive-bys`. You can see @vmbrasseur's 2017 talk on [Have It Your Way: Maximizing Drive-Thru Contributions](https://archive.org/details/ato2017-drivethru), which is where I first heard this term and started using it.

Brainstorming and ideation on what criteria defines drive-through contributions is helpful to expand this idea.

# Outcome

Common language and understanding of what drive-through contributions and contributors are, and the role of their contributions in the larger context of an Open Source project and/or ecosystem.

**Comment by GeorgLink** [comment]
Google Doc for developing the metric: https://docs.google.com/document/d/1Z1f1sL4169GlU5Dz2bhBiqPHrIsxMmyC6Rpj9UY-PW4/edit

---

Thanks @jwflory! I like the idea and started a google doc with the CHAOSS metric template where we can start the work on this.

**Comment by GeorgLink** [comment]
other terms: “episodic contributors” or “casual contributors” - https://opensource.com/article/17/10/managing-casual-contributors

**Comment by sgoggins** [comment]
Nadia Eghbal uses "drive by", Augur uses "fly by", and Cauldron uses "drive through" ... I'm wondering if the metric could include known synonyms, since some things are already written in books, and other publications. There seems to be some level of reification around different versions of this term. My concern would be that it could cause confusion if we don't acknowledge the synonyms in the metric itself.

**Comment by geekygirldawn** [comment]
I prefer episodic or drive-through.

**Comment by klumb** [comment]
I prefer episodic as well

**Comment by geekygirldawn** [comment]
I worry a little about episodic because I'm not sure if most non-native English speakers will have heard that term before, but as a data point, [DevStats uses Episodic](https://prometheus.devstats.cncf.io/d/14/new-and-episodic-pr-contributors?orgId=1&var-period=m&var-repogroup_name=All&from=now-1y&to=now-1M) and if you click that link and scroll down to below the graph, you can see how they define it.

**Comment by GeorgLink** [comment]
In some places, a synonym for `episodic volunteer` is `casual contributor`: https://opensource.com/article/17/10/managing-casual-contributors

**Comment by germonprez** [comment]
We seem to be landing on occasional contributors.
