### ISSUE TITLE
What Metric: Types of Contributions

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-common#40]
The D&I WG had been working on this metric https://github.com/chaoss/wg-diversity-inclusion/issues/116 and during the pull request review (https://github.com/chaoss/wg-diversity-inclusion/pull/153), we found that the metric has more common elements that are less focused on D&I.

The metric is developed here:

https://docs.google.com/document/d/1FJNsWimNN4KUgtCeq6z3etY_x3KJOrA376gCtOCIkzg/edit#

**Comment by germonprez** [comment]
I have made a first pass at suggested changes. Thanks for doing this @GeorgLink

**Comment by geekygirldawn** [comment]
I just left a bunch of suggestions as well, but I think we're getting really close!

**Comment by GeorgLink** [comment]
Thank you Matt and Dawn.

I reviewed and addressed  all comments and edits.

**Comment by jsmanrique** [comment]
Wow! Great doc. Thank you for the effort put on it. The list of "types" in the document is huge. I was expecting a more simple approach for 1st stage. 

I might be wrong, but my thought about this would be to focus in the primitives that define open source development: We have people (the "who") that contribute (the "what") to the project in a certain moment (the "when") and following a process (the "how").

For each primitive we might have certain primitive attributes, filters, parameters, or whatever we might want to call it. For example, for "contribution" (or the "what") we might have an small set of potential types:
* Code
* Issue
* Comment or message
* offline Meeting participation (rsvps)
* What else? Anything you cannot describe as code, issue, comment or offline meeting rsvp that cannot be assigned to a person doing something through a tool in a certain moment.

For each of these primitives we might end having values that might be used in metrics calculation:
* For Code (commits):
  * timestamp
  * author
  * topic
  * source
  * size
  * file/s
* For Issue
  * timestamp
  * author
  * topic
  * source
  * status
  * last update
* For Comments or messages
  * timestamp
  * author
  * topic
  * source
  * channel
  * thread
* For Meeting (rsvps)
  * timestamp
  * author
  * topic
  * source

There are several attributes common for these types, that relate them with the main primitives:
* timestamp: "when" the contribution has been made
* author: "who" has made the contribution
* topic: "what" describes the contribution
* source: "where" has been submitted the contribution

For each of these common attributes we might add later more information. For example:
* Based on the timestamp: timezone, day of the week, etc.
* Based on author information we might had: affiliation, geo info, gender, etc.
* Based on the topic: sentiment, kind of contribution (about security, about feature request, etc.)
* Based on the source: tool used, repository, etc.

What do you think? Again, perhaps I am trying to be very simplistic, but I love starting simple and get things done instead of going to very specific and get lost in the details.

**Comment by germonprez** [comment]
Hi @jsmanrique thanks for the comments. I believe these make sense. I'm not suggesting that we stick with the entire list of types but building from what we have and what you are talking about, I put together the following. It is not quite what you have... I'm just working with what was in the document. Each sub-type could then have your described low-level attributes. Am I on the right track? 

* Coding
  Bug Triaging
  Quality Assurance and Testing
  Security Related Activities Testing
  Localization/L10N and Translation
  User Interface, User Experience, and Accessibility

* Community Building and Management
  Documentation Authorship
  Teaching and Tutorial Building
  Troubleshooting and Support
  Creative Work and Design
  Event Organization
  Social Media Management
  User Support and Answering Questions
  Writing Articles
  Public Relations - Interviews with Technical Press
  Speaking at Events
  Marketing and Campaign Advocacy
  Website Development 
  Legal Council 
  * Financial Management

**Comment by jsmanrique** [comment]
I am not sure if I've understood you @germonprez.

The main list of types in the document looks more like a mix between topics and main types.

Perhaps my mix of semantic/graph database and objects oriented programming mindset is playing against me :-)

**Comment by germonprez** [comment]
I'm just trying to use what is in the document with what I read from you. Asking myself -- how can we bring what has been done and your insights together? Maybe I'll ask you if you could make comments in the document. That might help me understand your point.

**Comment by GeorgLink** [comment]
I sense a difference in perspective in this conversation. I think we are talking about different things here. 

When I started the list of contribution types, it was intended as a starting point for brainstorming. I had not actually intended to define what each data point is or how to get the data. I feel like @jsmanrique is arguing for the more detail level that is required for actual implementation.

My sense is that in this v2 release, the implementation details have taken a back seat in the metric definitions for the benefit of easier to consume metrics.

@jsmanrique, please do make suggestions in the Google doc, so that we can discuss the specifics.

**Comment by GeorgLink** [comment]
We moved forward this metric today. We left it at a high-level and less structured from what @jsmanrique suggested. We can improve in iterations but for now, I propose (#54) to accept this metric and @germonprez suggested to use this as a guinea pig for the rolling release cadence.
