### ISSUE TITLE
Release Candidate Comments (Types of Contributions)

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-common#56]
This issue provides a platform for feedback on the Types of Contributions metric as part of the Continuous Metric Contribution. Feedback period will end April 1, 2020. If no feedback is provided, we will consider this metric ready for release. 

The candidate metric can be found here: 
https://github.com/chaoss/wg-common/blob/master/focus-areas/what/types-of-contributions.md

**Comment by umutphp** [comment]
Many thanks to all Chaoss members for this great work :).

I have a question about the "Coding" contribution type. Does it contain code review or manual reviews in pull requests (or merge request in GitLab)?

**Comment by germonprez** [comment]
@umutphp I think that it certainly could.

**Comment by sgoggins** [comment]
I think a "code review" is a category of activity that is distinct from writing code, yet essential for producing and delivering quality code. My thoughts are that these are usually performed by more experienced members of a project.

**Comment by umutphp** [comment]
Hi @sgoggins,

You are almost right that the code review is done by more experienced members of the maintainers. But some project owners prefer to ask new contributors to make reviews to the other contributions. 

For example, If you create a new PR to [sindresorhus/awesome](https://github.com/sindresorhus/awesome) project, they ask you to review at least two other pull requests to review your pull request. I think they are asking it to make the new contributors read and understand the contribution guidelines. So, even if your pull request is not accepted, you will be a contributor by reviewing some other pull request.

I think It worths mentioning "review/code review" as a separate contribution type or under an existing contribution type.

**Comment by geekygirldawn** [comment]
This has been open for over a month for comment, so I think with the latest merge, we should be ready for release? What are the next steps @klumb?

**Comment by klumb** [comment]
This metric is not live on the site.

**Comment by mbbroberg** [comment]
I gave this a read through and it's an excellent introduction to the concept of types of contributors. 

My only addition is an example I really enjoy from the [All Contributors project](https://allcontributors.org/). It might be nice to add an example as well from the [p5.js project](https://github.com/processing/p5.js): 

![Screenshot from 2020-07-14 10-28-09](https://user-images.githubusercontent.com/1744971/87444835-eaadbe80-c5bc-11ea-8aaa-d7effb88c8e8.png)

**Comment by mbbroberg** [comment]
Happy to PR if others are into cc @germonprez

**Comment by germonprez** [comment]
@mbbroberg how does the types of contributions align with types of contributors? I'm just thinking as to how to bring these two, clearly related, terms together.

**Comment by mbbroberg** [comment]
@germonprez great point. I see ambiguity in the term "contribution" since it's used as both a descrete action as well as a position or status in a project. Separating the two, I see a a heavily overlapping Venn diagram where the **contributions** are more activity specific and **contributors** could be specific roles. For instance, I'm a maintainer **contributor** type, but my **contribution** is documentation, organizational leadership, advocacy, and other specific actions. 

The All Contributors project has a key of their classifications, which center on the contribution (action), not the status: 


Emoji/Type | Represents | Comments
:---: | :---: | :---:
🔊 <br /> `audio` | Audio | Podcasts, background music or sound effects
♿️ <br /> `a11y` | Accessibility | Reporting or working on accessibility issues
🐛 <br /> `bug` | Bug reports | links to issues reported by the user on this project
📝 <br /> `blog` | Blogposts | links to the blogpost
💼 <br /> `business` | Business Development | people who execute on the business end
💻 <br /> `code` | Code | links to commits by the user on this project
🖋 <br /> `content` | Content | e.g. website copy, blog posts are separate
🔣 <br /> `data` | Data | links to contributed data for the project (both tests and datasets)
📖 <br /> `doc` | Documentation | links to commits by the user on this project, Wiki, or other source of documentation
🎨 <br /> `design` | Design | links to the logo/iconography/visual design/etc.
💡 <br /> `example` | Examples | links to the examples
📋 <br /> `eventOrganizing` | Event Organizers | links to event page |
💵 <br /> `financial` | Financial Support | people or orgs who provide financial support, links to relevant page
🔍 <br /> `fundingFinding` | Funding/Grant Finders | people who help find financial support
🤔 <br /> `ideas` | Ideas & Planning | |
🚇 <br /> `infra` | Infrastructure | Hosting, Build-Tools, etc. Links to source file (like `travis.yml`) in repo, if applicable
🚧 <br /> `maintenance` | Maintenance | people who help in maintaining the repo, links to commits by the user on this project
📦 <br /> `platform` | Packaging | porting to support a new platform |
🔌 <br /> `plugin` | Plugin/utility libraries | links to the repo home
📆 <br/> `projectManagement` | Project Management | |
💬 <br /> `question` | Answering Questions | Answering Questions in Issues, Stack Overflow, Gitter, Slack, etc.
👀 <br /> `review` | Reviewed Pull Requests | |
🛡️ <br /> `security` | Security | identify and/or reduce security threats, GDPR, Privacy, etc
🔧 <br /> `tool` | Tools | links to the repo home
🌍 <br /> `translation` | Translation | links to the translated content
⚠️ <br /> `test` | Tests | links to commits by the user on this project
✅ <br /> `tutorial` | Tutorials | links to the tutorial
📢 <br /> `talk` | Talks | links to the slides/recording/repo/etc
📓 <br /> `userTesting` | User Testing | links to user test notes
📹 <br /> `video` | Videos | links to the video

We could consider assigning to this well-formed standard or another with input from TODO or related groups.

**Comment by GeorgLink** [comment]
Thanks @mbbroberg for your excellent observation and suggestion.

During the Common WG call today, we discussed about including "Types of Contributors" as part of the "Types of Contributions" or "Contributors". We think that "Types of Contributors" is a distinct metric that deserves its own page.

**Comment by mbbroberg** [comment]
glad it hit home @GeorgLink. I think all of the above could end up working, and lean toward the original "Types of Contributions" as long as it's elaborated on in the metric. Thinking out loud: the question itself could include a phrase like "what category of contribution" or maybe "How can we differentiate types of contribution by contributor?" 

I'll take a look at GNOME as well.

**Comment by geekygirldawn** [comment]
Closing this one for the release. We'll work on the other metric later.
